period=1000
failure_group_sz=3

[[peers]]
id=0

[peers.addr]
port=8000
host="127.0.0.1"

[[peers]]
id=1

[peers.addr]
port=8001
host="127.0.0.1"

[[peers]]
id=2

[peers.addr]
port=8002
host="127.0.0.1"
